#ifndef IRE_IKEYS_HPP
#define IRE_IKEYS_HPP

#define IREKEY_A                 1
#define IREKEY_B                 2
#define IREKEY_C                 3
#define IREKEY_D                 4
#define IREKEY_E                 5
#define IREKEY_F                 6
#define IREKEY_G                 7
#define IREKEY_H                 8
#define IREKEY_I                 9
#define IREKEY_J                 10
#define IREKEY_K                 11
#define IREKEY_L                 12
#define IREKEY_M                 13
#define IREKEY_N                 14
#define IREKEY_O                 15
#define IREKEY_P                 16
#define IREKEY_Q                 17
#define IREKEY_R                 18
#define IREKEY_S                 19
#define IREKEY_T                 20
#define IREKEY_U                 21
#define IREKEY_V                 22
#define IREKEY_W                 23
#define IREKEY_X                 24
#define IREKEY_Y                 25
#define IREKEY_Z                 26
#define IREKEY_0                 27
#define IREKEY_1                 28
#define IREKEY_2                 29
#define IREKEY_3                 30
#define IREKEY_4                 31
#define IREKEY_5                 32
#define IREKEY_6                 33
#define IREKEY_7                 34
#define IREKEY_8                 35
#define IREKEY_9                 36
#define IREKEY_0_PAD             37
#define IREKEY_1_PAD             38
#define IREKEY_2_PAD             39
#define IREKEY_3_PAD             40
#define IREKEY_4_PAD             41
#define IREKEY_5_PAD             42
#define IREKEY_6_PAD             43
#define IREKEY_7_PAD             44
#define IREKEY_8_PAD             45
#define IREKEY_9_PAD             46
#define IREKEY_F1                47
#define IREKEY_F2                48
#define IREKEY_F3                49
#define IREKEY_F4                50
#define IREKEY_F5                51
#define IREKEY_F6                52
#define IREKEY_F7                53
#define IREKEY_F8                54
#define IREKEY_F9                55
#define IREKEY_F10               56
#define IREKEY_F11               57
#define IREKEY_F12               58
#define IREKEY_ESC               59
#define IREKEY_TILDE             60
#define IREKEY_MINUS             61
#define IREKEY_EQUALS            62
#define IREKEY_BACKSPACE         63
#define IREKEY_TAB               64
#define IREKEY_OPENBRACE         65
#define IREKEY_CLOSEBRACE        66
#define IREKEY_ENTER             67
#define IREKEY_COLON             68
#define IREKEY_QUOTE             69
#define IREKEY_BACKSLASH         70
#define IREKEY_BACKSLASH2        71
#define IREKEY_COMMA             72
#define IREKEY_STOP              73
#define IREKEY_DOT               73
#define IREKEY_SLASH             74
#define IREKEY_SPACE             75
#define IREKEY_INSERT            76
#define IREKEY_DEL               77
#define IREKEY_HOME              78
#define IREKEY_END               79
#define IREKEY_PGUP              80
#define IREKEY_PGDN              81
#define IREKEY_LEFT              82
#define IREKEY_RIGHT             83
#define IREKEY_UP                84
#define IREKEY_DOWN              85
#define IREKEY_SLASH_PAD         86
#define IREKEY_ASTERISK          87
#define IREKEY_MINUS_PAD         88
#define IREKEY_PLUS_PAD          89
#define IREKEY_DEL_PAD           90
#define IREKEY_ENTER_PAD         91
#define IREKEY_PRTSCR            92
#define IREKEY_PAUSE             93
#define IREKEY_YEN               94
#define IREKEY_YEN2              95

#define IREKEY_MODIFIERS         96

#define IREKEY_LSHIFT            96
#define IREKEY_RSHIFT            97
#define IREKEY_LCONTROL          98
#define IREKEY_RCONTROL          99
#define IREKEY_ALT               100
#define IREKEY_ALTGR             101
#define IREKEY_LWIN              102
#define IREKEY_RWIN              103
#define IREKEY_MENU              104
#define IREKEY_SCRLOCK           105
#define IREKEY_NUMLOCK           106
#define IREKEY_CAPSLOCK          107

#define IREKEY_MAX               127


#define IRESHIFT_SHIFT            1
#define IRESHIFT_CONTROL          2
#define IRESHIFT_ALT              4

#endif
